### ISSUE TITLE
Proper package.json, to make npm install work

### ISSUE THREAD

**Issue by ranfdev** [sonnyp/troll#6]
I tried running `npm install https://github.com/sonnyp/troll.git` but I get
`
npm ERR! Cannot read properties of undefined (reading 'spec')
`

I think that's because the file package.json is missing many fields.

Could you run `npm init` in the repo to set the missing metadata?

**Comment by sonnyp** [comment]
I use troll as a git submodule – is that an option for you?

**Comment by ranfdev** [comment]
> I use troll as a git submodule – is that an option for you?

Yes, git submodules work, I just think having a real package keeps everything more organized.

**Comment by sonnyp** [comment]
Fixed by https://github.com/sonnyp/troll/pull/9
