### ISSUE TITLE
fetch fails when the server doesn't provide content-lenght header

### ISSUE THREAD

**Issue by ranfdev** [sonnyp/troll#7]
Error: `(gjs:128601): GLib-GIO-CRITICAL **: 17:04:08.949: g_input_stream_read_async: assertion 'buffer != NULL' failed`

The issue is the content-length, as specified in https://github.com/sonnyp/troll/blob/c3a682afef1e768cba1d67a5e2be52f064e6ba5b/src/std/fetch.js#L58-L60

Setting that value manually to a random number, like, 100, results in a successful response body.

Reproduce:

```js
        let res = await fetch({
            url: "https://lobste.rs/hottest.json", // lobsters doesn't set the "content-length" header
            headers: {
                "content-type": "application/json", 
                "user-agent": "fetch-polyfill-test"
            }
        });
        console.log(res)
        return await res.text() // fails

```

EDIT: reported directly to gnome-gjs, since this issue is present in one of the http examples https://gitlab.gnome.org/GNOME/gjs/-/issues/498

**Comment by sonnyp** [comment]
Andy shared an example of how to achieve this https://gitlab.gnome.org/GNOME/gjs/-/merge_requests/787

PR welcome!

From a (very) quick look at https://fetch.spec.whatwg.org - it looks like standard `fetch` doesn't even bother with `content-length` for reading body.

**Comment by sonnyp** [comment]
Probably a good idea to wait for the outcome of https://gitlab.gnome.org/GNOME/gjs/-/merge_requests/787#note_1523922
